---
title: "Analýza citlivosti povodí na klimatickou změnu"
author: "Martin Hanel et al."
date: "6 února 2018"
output: html_document
runtime: shiny
---



```{r, include=FALSE}
require(hySens)
require(plotly)
data("amerika")
data(delty)
data(stat)

bilan = amerika

#scen = sce[EXP=='obs', .(DTM, P = sP, T = sT)]

dta = data.table(bil.get.data(bilan))[, .(DTM, month = month(DTM), P, T)]
sce = delty[dta, on = 'month', allow = TRUE]
dta = dta[, .(month = month(DTM), SID = 'CTRL', PER = "CTRL", EXP = 'obs', dPR = 1, dTAS = 0, DTM, P, T)]
sce = rbind(dta, sce)

sce[, sP := P * dPR]
sce[, sT := T + dTAS]

```

```{r, include=FALSE}
vstat = melt(stat, id = 1:3, measure.vars = list(c(4:5), c(6:7)), value.name = c('P', 'T'))
vstat[, variable := factor(variable, labels = c('mean', 'sd'))]

ggplot(vstat) + geom_point(aes(x = P, y = T, shape = EXP, col = PER), size = 3, alpha = .5) + facet_wrap(~variable, scale = 'free', ncol = 2)

```

### Změny průměrů srážek a teploty a intenzita sezónního cyklu změn

```{r, echo = FALSE}

renderUI({
   plotOutput(
      'mean-sd',
      brush = brushOpts(
         id = 'Brush1'
      ),
      dblclick = dblclickOpts(id = 'DblClick1'),
      click = 'Click1'
   )
})



output[['mean-sd']] <- renderPlot({ 

   ggplot(vstat) + geom_point(aes(x = P, y = T, shape = EXP, col = PER), size = 3, alpha = .5) + facet_wrap(~variable, scale = 'free', ncol = 2) 
})
```

```{r, echo=FALSE}
renderTable()


xtable(data.frame(c('průměrná změna', "intenzita sezónního cyklu"), c(input$Click1$x) ))

Print(input$Click1)
```

